### ISSUE TITLE
VALIDATION_PROMPT is empty because of double initialization 

### ISSUE THREAD

**Issue by pavsh** [tantunholdings/medicare-insurance-api#2]
In Gpt.py lines 15 and 19:

VALIDATION_PROMPT = """
This is a medical insurance blog application. Ensure that the following question and additional file content (if applicable) are relevant to medical insurance topics, such as health coverage, claims, policies, or any other health services related to insurance. If the question is not relevant, respond with an error message saying "Invalid question. Please ask a question related to medical insurance. Also answer greetings such as Hello with a polite message.".
"""

VALIDATION_PROMPT = ""

**Comment by sahiruw** [comment]
The above prompt is strict so it does not respond to related questions as well. Can you update the prompt as you said?

**Comment by pavsh** [comment]
I updated the code myself.
